services:
  app:
    image: hellooptnc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8501"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network
    dns:
      - 1.1.1.1

networks:
  app_network:
    name: app_network
    driver: bridge
